name: Check
on:
  push:
    branches: [dev]
  pull_request:
permissions:
  contents: read
concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: jdx/mise-action@v4.3.0
      - run: mise run install
      - run: mise run check
      - name: Build for Vercel
        run: mise run build
        env:
          NITRO_PRESET: vercel
